Algoritmo "Soma"

//Problema "soma"
//Fazer um programa para ler dois valores inteiros X e Y, e depois mostrar na tela o valor da soma destes
//números.



Var

   x, y, soma : inteiro
   



Inicio

          escreva("Digite o valor de X: ")
          leia(x)
          
          escreva("Digite o valor de Y: ")
          leia(Y)
          
          soma <- x + y
          
          escreval("Soma = ",soma)



   



Fimalgoritmo